name: Scanner RSI OKX 1H

on:
  schedule:
    - cron: '5 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
  workflow_dispatch:

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Executar scanner RSI
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scanner.py
